# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_goal_duration_margin: 10.0

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    joints:
      - joint_base_yaw
      - joint_elbow_pitch
      - joint_shoulder_pitch
      - joint_shoulder_roll
      - joint_tool_insertion
      - joint_wrist_pitch
      - joint_wrist_roll
    action_ns: follow_joint_trajectory
    default: True

