# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    
    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
arm_group_controller:      
  ros__parameters:
    joints:
      - joint_base_yaw
      - joint_elbow_pitch
      - joint_shoulder_pitch
      - joint_shoulder_roll
      - joint_tool_insertion
      - joint_wrist_pitch
      - joint_wrist_roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true


